version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: .docker/development/Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .docker/development/certs:/var/www/ssl
